export const FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAILED = "USER_CREATE_FAILED";

export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_FAILED = "PROJECT_CREATE_FAILED";

export const CREATE_FILE_SUCCESS = "CREATE_FILE_SUCCESS";
export const FILE_OPERATION_FAILURE = "FILE_OPERATION_FAILURE";
export const GET_FILE_SUCCESS = "GET_FILE_SUCCESS";
export const UPDATE_FILE_SUCCESS = "UPDATE_FILE_SUCCESS";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
